### ISSUE TITLE
section과 div

### ISSUE THREAD

**Issue by woochul2** [Dev-Mentoring-Platform/frontend#13]
지금 많은 컴포넌트가 `section` 태그로 감싸져 있는데요, 이걸 `div`로 바꾸면 어떨까요?
[MDN section 문서](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)를 보면 `section` 태그는 `h2`와 같은 헤딩과 관련 내용을 담을 때 사용하는 것 같아요. 헤딩을 포함하지 않는 컴포넌트에도 `section` 태그를 쓰는 건 시맨틱하지 않다는 생각이 드는데, 어떻게 생각하시나요?

**Comment by ssu00** [comment]
저는 div에 아무 의미가 없다고 생각해서 컴포넌트들을 section으로 감싸 사용했었어요. 올려주신 문서 보니까 바꾸는 것도 괜찮을 것 같습니다! 다만 div 말고 사용할만한 태그가 있는지 조금 더 찾아보고 다시 이슈 올릴게요!!
