### ISSUE TITLE
MENTEE: 홈

### ISSUE THREAD

**Issue by ssu00** [Dev-Mentoring-Platform/frontend#57]
## **📝 이슈 내용**
배포 전, 전체 페이지의 테스트가 필요하다고 생각해 테스트를 진행하려고 합니다. 
<br/><br/>

## **✔ 체크리스트**
- [ ] 접속 안 되는 페이지 있는지
- [ ] 멘토, 멘티, 멘토릿지로 변경되었는지
- [ ] name 대신 nickname 사용 중인지
- [ ] 데이터가 유효한지
- [ ] 예외처리가 알맞게 되었는지
- [ ] 라우팅이 제대로 되는지

**Comment by ssu00** [comment]
@Salvation-sub @yeonkyungJoo 
1. 멘티 홈에 검색 기능이 구현되어 있는지
2. 서울시 동작구, 서울시 관악구 같은 dropdown은 필터링할 때에 사용하는건지
궁금합니다!

+ 필터링에 "초기화" 기능도 구현되어야 할 것 같아요!

**Comment by ssu00** [comment]
@yeonkyungJoo
1. db에서 lecture 테이블의 approved를 따로 업데이트해주지 않으면, 멘티의 홈에서 멘토가 등록한 강의를 볼 수 없는 것 같습니다. 현재 db에서 따로 업데이트를 하며 테스트 중인데, 혹시 배포한 후에도 db에서 업데이트를 해주면 되는 것인지 궁금합니다!

**Comment by yeonkyungJoo** [comment]
> @yeonkyungJoo
> 1. db에서 lecture 테이블의 approved를 따로 업데이트해주지 않으면, 멘티의 홈에서 멘토가 등록한 강의를 볼 수 없는 것 같습니다. 현재 db에서 따로 업데이트를 하며 테스트 중인데, 혹시 배포한 후에도 db에서 업데이트를 해주면 되는 것인지 궁금합니다!

@ssu00 
이건 관리자페이지를 만들어야하는데
일단 우선순위가 아니라고 판단해서 뒤로 미뤘어요.
사용자에게 보여지는 건 아니라서!!
이건 이번주 회의 때 한번 얘기해보면 좋을 것 같아요!
