### ISSUE TITLE
MENTEE: 마이페이지 - 신청한 강의, 위시리스트

### ISSUE THREAD

**Issue by ssu00** [Dev-Mentoring-Platform/frontend#60]
## **📝 이슈 내용**
배포 전, 전체 페이지의 테스트가 필요하다고 생각해 테스트를 진행하려고 합니다. 
<br/><br/>

## **✔ 체크리스트**
- [ ] 접속 안 되는 페이지 있는지
- [ ] 멘토, 멘티, 멘토릿지로 변경되었는지
- [ ] name 대신 nickname 사용 중인지
- [ ] 데이터가 유효한지
- [ ] 예외처리가 알맞게 되었는지
- [ ] 라우팅이 제대로 되는지

**Comment by ssu00** [comment]
@Salvation-sub 
멘티 위시리스트에 데이터가 하나씩밖에 안 뜨는 것 같아요! 확인 한번 부탁드립니다~!!

**Comment by ssu00** [comment]
@yeonkyungJoo 
혹시 enrollment 테이블의 checked, checked_at이 언제 업데이트되는지 알 수 있을까요? 강의를 신청해도 checked와 checked_at을 업데이트해주지 않으면, 신청한 강의 목록에 안 뜨는 것 같아서요!

**Comment by yeonkyungJoo** [comment]
> @yeonkyungJoo 혹시 enrollment 테이블의 checked, checked_at이 언제 업데이트되는지 알 수 있을까요? 강의를 신청해도 checked와 checked_at을 업데이트해주지 않으면, 신청한 강의 목록에 안 뜨는 것 같아서요!

멘티가 강의 신청을 해도
멘토가 승인을 해줘야 해요.
저희가 아직 '신청 승인' 버튼을 추가하지 않았어요!!
